version: 2
jobs:
  build:
    docker:
      - image: php:7.3-fpm-alpine
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Checkout the sourcecode
          command: |
            set -x
            ./vendor/bin/phpstan analyze --level=5 wtnb-test.php --memory-limit 1G --no-progress